### ISSUE TITLE
怎么才能运行起来?

### ISSUE THREAD

**Issue by virtualpeer** [Ceruleanacg/Personae#10]

**Comment by Ceruleanacg** [comment]
It would be appreciated if you could take time to read the README.md first, there are instructions. If you have problem, you can open an issue here to discuss, thank you very much.

**Comment by wangzhangup** [comment]
哥们，我帮你简单指导一下。
首先，需要一台有Nvidia GPU的机器，并安装Ubuntu。
第二步，安装Nvidia-docker2。
然后，git clone https://github.com/Ceruleanacg/Personae.git
最后：
cd Personae
sudo docker image build -t ppdemo .
sudo docker run --name my_mongo -p 27017:27017 -d mongo
sudo docker run -t --link my_mongo:mongo -v $PWD:/app/Personae ppdemo spider/stock_spider.py
sudo nvidia-docker run -t --link my_mongo:mongo -v $PWD:/app/Personae ppdemo algorithm/SL/DualAttnRNN.py

另外，请尽量用英文提问吧

**Comment by virtualpeer** [comment]
thinks a lot

**Comment by virtualpeer** [comment]
thanks a lot
