### ISSUE TITLE
error in run with docker

### ISSUE THREAD

**Issue by Hannah-F** [Ceruleanacg/Personae#12]
Hey, I try to run with docker, but I' m not familiar with it , I also download the Kitematic , and your images . Then I run 
docker run -t -v /Users/fanpu/Personae:/app  --network=bridge  ceruleanwang/haru DoubleDQN.p
python3.5: can't open file 'DoubleDQN.py': [Errno 2] No such file or directory 
Could u pls help me solve the error? Thanks.

**Comment by Ceruleanacg** [comment]
Sorry, it's because I didn't update the README.md to the latest version, and now it is, so the code to run the algorithm should be,
```
docker run -t -v local_project_dir:docker_project_dir --network=yuor_network ceruleanwang/personae algorithm/RL or SL/algorithm_name.py
```
Try to replace the `ceruleanwang/haru` to `ceruleanwang/personae`, if you have further questions, you could also add my WeChat 17392810723 : )
