### ISSUE TITLE
a problem about config

### ISSUE THREAD

**Issue by cathy0213** [Ceruleanacg/Personae#13]
Hello, I tried to run "TreNet.py", but it can not find config in algorithm

from algorithm import config
ImportError: No module named 'algorithm'

I don't know how to find "config" , maybe i should do something first? 
How to solve this problem? Could you help me ? Sorry, I'm new here. 
Thank you.

**Comment by cathy0213** [comment]
sorry, may be it's my env wrong, not your problem. I can not import base,too.

**Comment by cathy0213** [comment]
Yeah,that's my problem! I'm so sorry and I can't find you in WeChat. Is it correct ?
Thank you very much.

**Comment by Ceruleanacg** [comment]
Oh sorry, WeChat is 610261753 or 17392810723
