### ISSUE TITLE
Question about the mix_index_state

### ISSUE THREAD

**Issue by xiaoqinzhe** [Ceruleanacg/Personae#15]
Of the Market initial function parameters, the mix_index_state mean that whether the index code 'sh' is included into market's code. I want to know that whether the code 'sh' is a stock/future index data and if yes, how can i get it and why you use it? Hope you can give me response, thank you very much!

**Comment by Ceruleanacg** [comment]
Sorry for the confusing parameters in the options, I have not updated the options doc in time.

`mix_index_state` is a option that decides whether the state or sequence data will concatenate index data like SH000001.

- Whether the code 'sh' is a stock/future index data    
`sh` here is index code of 000001.

- If yes, how can I get it and why you use it   
you can run the spider setting the code to be 000001 to get `sh`, the reason why I use it is that this mixture might give the agent or predictor a big picture of market.

Thank you very much.

**Comment by JS00000** [comment]
Can we set mix_index_state=false? But if I did this, something got wrong.
```
Traceback (most recent call last):
  File "algorithm/SL/NaiveLSTM.py", line 108, in <module>
    main(model_launcher_parser.parse_args())
  File "algorithm/SL/NaiveLSTM.py", line 103, in main
    algorithm.run()
  File "/Users/yyx/Documents/Code/python/price_prediction/Personae/base/algorithm/model.py", line 242, in run
    self.train()
  File "algorithm/SL/NaiveLSTM.py", line 55, in train
    _, loss = self.session.run([self.train_op, self.loss], feed_dict={self.x: batch_x, self.label: batch_y})
  File "/Users/yyx/anaconda/envs/py35/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/Users/yyx/anaconda/envs/py35/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1096, in _run
    % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (32, 1) for Tensor 'Placeholder_1:0', which has shape '(?, 2)'
```

**Comment by Ceruleanacg** [comment]
Sorry! That’s my fault, I wrote a bug when a add the feature of `mix_index_state`, now it has been fixed, sorry for that.
