### ISSUE TITLE
It seems that the RL algorithms under default parameters didn't learn anything.

### ISSUE THREAD

**Issue by xtyangjie** [Ceruleanacg/Personae#22]
Another question(It can be found in my mail, too) is as shown in the title. I am puzzled whether I had misunderstanded. Please help me to realize it...

I ran 3 alogrithms of  NaiveLSTM, TreNet and Attention. After training, the predictions were plotted. While I made a tiny change on the plotting method - I **added the close price at time t in x, to compare it with real and predict**. Then in the figure, there were now 3 lines:
* x - close price at **time t**, which is **newly added and from real data**;
* real - close price at **time t+1**, which is from **real data**;
* predict - close price at **time t+1**, which is **predicted** and to be validated.

What puzzled me is **the predict line approximated much more with x instead of with real** in the result of all the three algorithms. In my former experiments, I used some form of simple functions such as sin(x) as a sequence, and plotted x, real, and predict. **On these simple sequences the predict lines approximate the real(y, time t+1) perfectly**.

As a result, I have got a question **whether the algorithms learned anything**. Please give me some help...

Following 3  plots are NaiveLSTM, the whole plot of Attention, and a local figure in the plot of Attention. In all of which, there 3 lines indicating x(just close price at **time t**, real, and predict).
1. NaiveLSTM
![image](https://user-images.githubusercontent.com/536122/42073546-fe93d570-7b99-11e8-84d0-0dd6921b71ce.png)
2. Whole plot of Attention (In which the detail is hard to distinct)
![image](https://user-images.githubusercontent.com/536122/42073576-1cb8f7b0-7b9a-11e8-9256-fc6e29b7099a.png)
3. A local figure of Attention
![3](https://user-images.githubusercontent.com/536122/42073675-bedde122-7b9a-11e8-866d-8c7924877b54.png)

Thanks very much!

**Comment by Ceruleanacg** [comment]
We had a talk in WeChat.
